#!/bin/bash
#local script to run PSO files
./perfeval_spmd.out searchParams_SimDATASKA.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/TESTDATA_HDF5/GWBsimDataSKASrlz1Nrlz1.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/Out/GWBsimDataSKASrlz1Nrlz1.hdf5 maxPhase
./perfeval_spmd.out searchParams_SimDATASKA.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/TESTDATA_HDF5/GWBsimDataSKASrlz1Nrlz2.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/Out/GWBsimDataSKASrlz1Nrlz2.hdf5 maxPhase
./perfeval_spmd.out searchParams_SimDATASKA.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/TESTDATA_HDF5/GWBsimDataSKASrlz1Nrlz3.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/Out/GWBsimDataSKASrlz1Nrlz3.hdf5 maxPhase
./perfeval_spmd.out searchParams_SimDATASKA.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/TESTDATA_HDF5/GWBsimDataSKASrlz1Nrlz4.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/Out/GWBsimDataSKASrlz1Nrlz4.hdf5 maxPhase
./perfeval_spmd.out searchParams_SimDATASKA.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/TESTDATA_HDF5/GWBsimDataSKASrlz1Nrlz5.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/Out/GWBsimDataSKASrlz1Nrlz5.hdf5 maxPhase
./perfeval_spmd.out searchParams_SimDATASKA.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/TESTDATA_HDF5/noise1.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/Out/noise1.hdf5 maxPhase
./perfeval_spmd.out searchParams_SimDATASKA.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/TESTDATA_HDF5/noise2.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/Out/noise2.hdf5 maxPhase
./perfeval_spmd.out searchParams_SimDATASKA.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/TESTDATA_HDF5/noise3.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/Out/noise3.hdf5 maxPhase
