#!/bin/bash
#shell script to run PSO on local laptop
./perfeval_spmd.out /Users/qianyiqian/Research/PulsarTiming/SimDATA/searchParams_HDF5/searchParams_GWBsimDataSKA1.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/TESTDATA_HDF5/GWBSimDATASKASrlz1Nrlz1.hdf5/Users/qianyiqian/Research/PulsarTiming/SimDATA//RESULTS/searchParams_GWBsimDataSKA1.hdf5 MaxPhase
./perfeval_spmd.out /Users/qianyiqian/Research/PulsarTiming/SimDATA/searchParams_HDF5/searchParams_GWBsimDataSKA10.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/TESTDATA_HDF5/GWBSimDATASKASrlz1Nrlz1.hdf5/Users/qianyiqian/Research/PulsarTiming/SimDATA//RESULTS/searchParams_GWBsimDataSKA10.hdf5 MaxPhase
./perfeval_spmd.out /Users/qianyiqian/Research/PulsarTiming/SimDATA/searchParams_HDF5/searchParams_GWBsimDataSKA2.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/TESTDATA_HDF5/GWBSimDATASKASrlz1Nrlz1.hdf5/Users/qianyiqian/Research/PulsarTiming/SimDATA//RESULTS/searchParams_GWBsimDataSKA2.hdf5 MaxPhase
./perfeval_spmd.out /Users/qianyiqian/Research/PulsarTiming/SimDATA/searchParams_HDF5/searchParams_GWBsimDataSKA3.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/TESTDATA_HDF5/GWBSimDATASKASrlz1Nrlz1.hdf5/Users/qianyiqian/Research/PulsarTiming/SimDATA//RESULTS/searchParams_GWBsimDataSKA3.hdf5 MaxPhase
./perfeval_spmd.out /Users/qianyiqian/Research/PulsarTiming/SimDATA/searchParams_HDF5/searchParams_GWBsimDataSKA4.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/TESTDATA_HDF5/GWBSimDATASKASrlz1Nrlz1.hdf5/Users/qianyiqian/Research/PulsarTiming/SimDATA//RESULTS/searchParams_GWBsimDataSKA4.hdf5 MaxPhase
./perfeval_spmd.out /Users/qianyiqian/Research/PulsarTiming/SimDATA/searchParams_HDF5/searchParams_GWBsimDataSKA5.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/TESTDATA_HDF5/GWBSimDATASKASrlz1Nrlz1.hdf5/Users/qianyiqian/Research/PulsarTiming/SimDATA//RESULTS/searchParams_GWBsimDataSKA5.hdf5 MaxPhase
./perfeval_spmd.out /Users/qianyiqian/Research/PulsarTiming/SimDATA/searchParams_HDF5/searchParams_GWBsimDataSKA6.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/TESTDATA_HDF5/GWBSimDATASKASrlz1Nrlz1.hdf5/Users/qianyiqian/Research/PulsarTiming/SimDATA//RESULTS/searchParams_GWBsimDataSKA6.hdf5 MaxPhase
./perfeval_spmd.out /Users/qianyiqian/Research/PulsarTiming/SimDATA/searchParams_HDF5/searchParams_GWBsimDataSKA7.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/TESTDATA_HDF5/GWBSimDATASKASrlz1Nrlz1.hdf5/Users/qianyiqian/Research/PulsarTiming/SimDATA//RESULTS/searchParams_GWBsimDataSKA7.hdf5 MaxPhase
./perfeval_spmd.out /Users/qianyiqian/Research/PulsarTiming/SimDATA/searchParams_HDF5/searchParams_GWBsimDataSKA8.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/TESTDATA_HDF5/GWBSimDATASKASrlz1Nrlz1.hdf5/Users/qianyiqian/Research/PulsarTiming/SimDATA//RESULTS/searchParams_GWBsimDataSKA8.hdf5 MaxPhase
./perfeval_spmd.out /Users/qianyiqian/Research/PulsarTiming/SimDATA/searchParams_HDF5/searchParams_GWBsimDataSKA9.hdf5 /Users/qianyiqian/Research/PulsarTiming/SimDATA/TESTDATA_HDF5/GWBSimDATASKASrlz1Nrlz1.hdf5/Users/qianyiqian/Research/PulsarTiming/SimDATA//RESULTS/searchParams_GWBsimDataSKA9.hdf5 MaxPhase
