% convert search parameters file form .mat to .json
% NOTE: need to install JSONlab toolbox
clear;
load('searchParams_GWBsimDataSKA.mat');
filename = 'Nyquist';
data = struct('band_num',0.0,... % initial value
    'alpha',[xmaxmin(1,1),xmaxmin(1,2)],...
    'delta',[xmaxmin(2,1),xmaxmin(2,2)],...
    'angular_velocity',[xmaxmin(3,1),xmaxmin(3,2)],...
    'phi0',[xmaxmin(4,1),xmaxmin(4,2)],...
    'amplitude',[xmaxmin(5,1),xmaxmin(5,2)],...
    'inclination',[xmaxmin(6,1),xmaxmin(6,2)],...
    'polarization',[xmaxmin(7,1),xmaxmin(7,2)]);

file = jsonencode(data);
savejson('',file,[filename,'.json']);
save([filename,'.txt'],'xmaxmin','-ascii','-double','-tabs'); 